# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8aa9afcecaf0746ccab12974c7ac9c5766ba3cb597032aafa2c7f259cf3a4887e8dc398b74cced3e700e8f9814a897c865684b0ec34a7b1fef234f3f117576a

test:
  secret_key_base: 5648ae38d05d81434482c638e1e31e84cb33296cdfe8218db23deec94954e9db5638b0b3b67552c1b854ee4ef87f425089fb98d6b960a71249c31e66655d2b4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
